/**
 * Regenerates skills/sepia/references/tools.md from the Valibot schemas in
 * @sepia/shared. Run with: bun run scripts/gen-skill-ref.ts
 *
 * The generated file is the per-tool reference the SKILL.md links to. It is
 * checked in (so the skill works without a build step), but this script keeps
 * it in sync with the schemas.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  TOOL_NAMES,
  DEFAULT_NAMESPACE,
  MEMORY_TYPES,
  IMPORTANCE_MIN,
  IMPORTANCE_MAX,
  DEFAULT_IMPORTANCE,
  MAX_ENTITY_LINKS,
  SEARCH_LIMIT_MAX,
  QUERY_LIMIT_MAX,
  TRAVERSE_DEPTH_MAX,
} from "@sepia/shared";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, "../skills/sepia/references/tools.md");

const lines: string[] = [];
lines.push("# Sepia — Tool Reference");
lines.push("");
lines.push(
  "The 7 MCP tools, their input shapes, and example calls. Source of truth:",
);
lines.push(
  "`packages/shared/src/schemas.ts` (`@sepia/shared`). Regenerated by",
);
lines.push("`scripts/gen-skill-ref.ts` — do not hand-edit.");
lines.push("");

const sections: Record<string, string[]> = {
  manage_namespace: [
    "Actions: `create` | `list` | `get` | `delete`",
    "",
    '- `create`: name (string, 1-64), description? (string, default "")',
    "- `get`: id (uuid) — or name (string, 1-64)",
    "- `delete`: id (uuid) — cascades entities → relations/memories via FKs",
    "- `list`: no args — returns namespaces with entity/memory/relation counts",
  ],
  manage_entity: [
    "Actions: `create` | `get` | `update` | `delete` | `find` | `batch_update`",
    "",
    '- `create`: entity { name (1-200), type (1-64), summary? (""), importance? (0-1, default 0.5), metadata? ({}), tags? (string[], max 10) } — type auto-normalized to person|project|tool|concept|repo (unknown → concept + tag)',
    "- `get`: id (uuid) — returns entity + linked memories + in/out relations",
    "- `update`: id (uuid) + update { any subset of name/type/summary/importance/metadata/tags } — tags REPLACES the set",
    "- `delete`: id (uuid)",
    '- `find`: query (name to match, exact or substring) + type? (filter) + namespace? (default "personal") — up to 10 results',
    "- `batch_update`: where { type? / namespace? / query? } (at least one) + update { any subset } + batch_limit? (default 100, max 500) — updates ALL matching entities, returns count",
  ],
  manage_relation: [
    "Actions: `create` | `delete` | `list`",
    "",
    "- `create`: relation { source_id (uuid), target_id (uuid), relation_type (1-64), weight? (0-1, default 0.5) } — on UNIQUE(source, target, relation_type) conflict, **updates weight** instead of erroring",
    "- `delete`: id (uuid)",
    "- `list`: by entity_id (in + out) or by namespace",
  ],
  manage_memory: [
    "Actions: `create` | `get` | `update` | `delete` | `query` | `batch_update` | `ingest`",
    "",
    `- \`create\`: memory { content (1-4000), type? (${MEMORY_TYPES.join("|")}, default fact), importance? (0-1, default 0.5), namespace? (default "${DEFAULT_NAMESPACE}"), entity_ids? (uuid[], max ${MAX_ENTITY_LINKS}), metadata? ({}), tags? (string[], max 10) }`,
    "- `get`: id (uuid) — includes entity links",
    "- `update`: id (uuid) + update { any subset of content/type/importance/metadata/tags; entity_ids REPLACES the link set, tags REPLACES the tag set }",
    "- `delete`: id (uuid)",
    `- \`query\`: filters type? / namespace? (default "${DEFAULT_NAMESPACE}") / importance_min? (0-1) / archived? (default false) / tags? (match ALL); order importance DESC, updated_at DESC; limit default 20, max ${QUERY_LIMIT_MAX}`,
    "- `batch_update`: where { type? / namespace? / tags? / importance_min? / q? } (at least one) + update { any subset } + batch_limit? (default 100, max 500) — updates ALL matching memories, returns count",
    "- `ingest`: conversation { summary (1-4000), conversation_id (1-200), title? (1-200, human-readable name — how conversations are told apart when resuming), status? (active|paused|done, default active), decisions? / preferences? / instructions? / observations? / open_questions? (string[], each ≤4000), entities? [{name, type, summary?}], source? {ai, ref?}, transcript? (≤100k, optional — only if the raw log exists), namespace?, tags? } — atomically saves a distilled conversation: digest memory (tag `conversation`, importance 0.85, metadata.kind=conversation + title/status, protected from consolidation) + constituent memories (decisions→fact, preferences→preference, instructions→instruction, observations→observation, open_questions→observation tagged `open-question`, all with metadata.conversation_id) + entities (find-or-create). One digest per major topic, same conversation_id groups them. Use when the user says 'save this conversation' or switches AIs mid-task. Resume: prefer status=active; mark done by updating digest metadata.status (metadata REPLACES — get first).",
  ],
  search: [
    "- `q` (string, 0-200, required) — case-insensitive substring match over `memories.content`, `entities.name`, `entities.summary`; empty string returns recent items",
    "- `namespace`? (string) — scope the search",
    "- `type`? (string) — memory type (fact|observation|preference|instruction) OR entity type (person|project|tool|concept|repo)",
    "- `tags`? (string[]) — match memories/entities carrying ALL of these tags",
    `- \`limit\`? (1-${SEARCH_LIMIT_MAX}, default 10)`,
    "- Multi-word `q` = AND-of-words (every word must appear, any order); exact-phrase matches rank first.",
    "- Returns merged, de-duplicated list with `kind` (memory|entity), id, snippet, score. Rank: exact word match > substring match, then importance DESC, then updated_at DESC. Empty `q` → recent items.",
  ],
  traverse_graph: [
    "- `start_id` (uuid, required) — BFS walk from this entity",
    `- \`depth\`? (1-${TRAVERSE_DEPTH_MAX}, default 1) — number of hops`,
    "- Returns nodes + edges within N hops of the start entity.",
  ],
  consolidate: [
    "- No input args.",
    "- Idempotent maintenance sweep: decay-scoring, dedup (trimmed case-insensitive exact content match → keep highest importance, archive the rest), purge archived. Pure SQL, no LLM calls.",
  ],
};

for (const name of TOOL_NAMES) {
  lines.push(`## ${name}`);
  lines.push("");
  lines.push(...(sections[name] ?? ["(no reference — see schemas.ts)"]));
  lines.push("");
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join("\n"));
console.log(`wrote ${OUT}`);
